### PR TITLE
test: add benchmark for shapes

### PR DESCRIPTION
**Pull request by andreivladbrg**

### CODE REVIEW

**Comment by andreivladbrg** [comment]
I realized that these gas estimations might be higher, since the `create` functions in creator contract include additional logic instead of directly calling the core create function with some params.

~~However, in the app, we use only the `Batch` contract to create streams, which might end up being accurate after all~~

wdyt? @smol-ninja

**Comment by andreivladbrg** [comment]
Tested on [sepolia](https://sepolia.etherscan.io/tx/0x85b2f96529e75a4670ad26c925638156f1b89af68654639eeee9317374c097be) and the gas for a timelock shape stream using batch contract is _364,698_ which is actually more than what is returned by `createStream_Timelock`: _305,265_

image

**Comment by smol-ninja** [comment]
Wouldn't it be more useful to publish results for the actual gas usage through the UI i.e. via `SablierV2Batch` contract. What are your thoughts on this @andreivladbrg?

PS: why not `console2` in `src` files?

**Comment by andreivladbrg** [comment]
> Wouldn't it be more useful to publish results for the actual gas usage through the UI

I made a mistake comparing it to the gas used in the app because the request was made specifically for smart contract integration, for which these estimations are accurate:

image

I think it would be better to include those gas estimations (from calling `SablierV2Batch`) in the app itself rather than in the docs. I am pretty sure that the library used in the app (wagmi) offers a utility function to estimate the gas cost before actually calling it, am I wrong @razgraf ?

**Comment by andreivladbrg** [comment]
>PS: why not console2 in src files?

I was thinking about this, but I don't think this is a good idea since that code is shown in the [docs](https://docs.sablier.com/contracts/v2/guides/create-stream/lockup-dynamic#the-complete-lockup-dynamic-stream-creator-contract) at the guides section.

It would cause confusion.

**Comment by razgraf** [comment]
We have gas estimations sure, and showing an approximation is an interesting idea. But IMO end users shouldn't really inform their choice of a distribution curves based on gas consumption, rather on how it best fits their business needs.

There's also a bunch of considerations to make (which are easier to go at length over, in the docs) about caveats like: custom token transfer methods increasing gas costs, using the batch contract vs. creating streams with the lockup contracts directly etc.

So I'd keep this only in the docs for now.

**Comment by andreivladbrg** [comment]
> There's also a bunch of considerations to make (which are easier to go at length over, in the docs) about caveats like: custom token transfer methods increasing gas costs, using the batch contract vs. creating streams with the lockup contracts directly etc

Agree, but this would take time. 
I wanted with this PR to offer a fast gas estimation(maybe not so accurate depending on the method chose to interact with core contracts).

**Comment by smol-ninja** [comment]
How about instead of having `console2` in `test`, we take the following approach:
1. Estimate the actual gas from within `src` files
2. Add those numbers in the doc
3. Remove `console2` from `src` files.

We don't really need that code here as long as the gas estimations are present in the docs.

**Comment by andreivladbrg** [comment]
>Estimate the actual gas from within src files
Add those numbers in the doc

agree, we can simply do this for the time being

> Remove console2 from src files.

we don't need to remove them,  but we can keep on a separate branch which is referenced only in the docs
i will close this PR

--- 

for a detailed gas estimation section, we can use your work from the [PR](https://github.com/sablier-labs/v2-core/pull/908), which we will eventually need for `SablierV2Batch` as well

**Comment by smol-ninja** [comment]
Agree with what you have said.

> for a detailed gas estimation section, we can use your work from the https://github.com/sablier-labs/v2-core/pull/908, which we will eventually need for SablierV2Batch as well

OK sounds good. I will add them to periphery as well.

**Comment by andreivladbrg** [comment]
created this branch: https://github.com/sablier-labs/examples/tree/shapes-benchmark

**Pull request closed without merging**
