### PR TITLE
Add Stream Management with Hook Example

### PR DESCRIPTION
**Pull request by josechifflet**
#### **Summary**
This PR introduces a new example demonstrating the integration of Sablier V2 streams with the ability to add custom restrictions on withdrawals using hooks. The example includes a smart contract (`StreamManagementWithHook.sol`) and a comprehensive test suite showcasing stream creation, withdrawal, and management functionalities.

#### **Example Contract Details**
- The `StreamManagementWithHook` contract enables the creation, management, and withdrawal of Sablier V2 streams with additional custom logic implemented via hooks.

- Streams created by this contract are non-transferable, as the recipient of the stream is this contract, making it the owner of the Sablier lockup ERC721 token. As the token owner, only this contract can perform owner-specific operations on the ERC721 token.

**Hooks:**  
The example contract implements the `ISablierLockupRecipient` interface, overriding the `onSablierLockupWithdraw` and `onSablierLockupCancel` hooks.  
- The `onSablierLockupWithdraw` hook restricts withdrawals so that only this management contract can execute them. Calls to the Sablier V2 `withdraw` function will revert if the caller is not this contract. This ensures that the process of withdrawing tokens cannot be altered or bypassed.

- The `onSablierLockupCancel` hook is also implemented. However, due to the nature of the Sablier V2 `cancel` function, it is unnecessary to check if the caller is this contract, as the stream sender is always the management contract. Thus, only this contract can call the `cancel` function, making a similar check to the `onSablierLockupWithdraw` hook redundant.

#### **Unit Test Details**
The test suite verifies the functionality of the `StreamManagementWithHook` contract, covering the following scenarios:

- **Stream Creation**: Verifies that streams are created correctly with proper token transfers and stream parameters.

- **Withdrawal Restrictions**: Ensures that unauthorized attempts to withdraw directly from Sablier revert due to the custom hook implementation.

- **Withdrawals via the Management Contract**: Validates that only the management contract can execute withdrawals, ensuring that the correct recipient receives the tokens and the stream is properly depleted.

- **ERC721 Operations**: Tests that ERC721 operations, such as transfer and burn, revert if the stream is not fully depleted. Also ensures that the stream token is burned once it is fully depleted.

#### **Running the Tests**
To run the tests, use the following command:
```
forge test --match-contract StreamManagementWithHookTest      
```

```
Ran 5 tests for v2/core/StreamManagementWithHook.t.sol:StreamManagementWithHookTest
[PASS] test_ERC721_operations_revert() (gas: 306697)
[PASS] test_create() (gas: 277244)
[PASS] test_withdrawMax_from_management() (gas: 313196)
[PASS] test_withdraw_from_management() (gas: 328936)
[PASS] test_withdraw_from_sablier_reverts() (gas: 388688)
Suite result: ok. 5 passed; 0 failed; 0 skipped; finished in 1.20ms (1.32ms CPU time)

Ran 1 test suite in 123.73ms (1.20ms CPU time): 5 tests passed, 0 failed, 0 skipped (5 total tests)
```

### CODE REVIEW

**Comment by smol-ninja** [comment]
Great work and thank you @josechifflet for the PR.  We will review it at the earliest.

**Review by smol-ninja — APPROVED** [review]
Thanks for the PR @josechifflet. I was finally able to spend last night to review your code. Fantastic work 🙇

A few suggestions (which I implemented myself in https://github.com/sablier-labs/examples/pull/35/commits/bfad32197d39a343a356457af8d225c76732e281):
- Natspec comments requires some polishing
- Trimmed down some function which does not provide new knowledge such as `cancel` is obvious imo once someone has gone through `withdraw` logic. Wdyt?
- Refactored tests to follow Sablier coding practices
- Polished example code with modifier and a stream beneficiar getter

I assume that you may not have time to change the code based on my comment so I decided to do it myself while reviewing it. Feel free to have a look at [my commit](https://github.com/sablier-labs/examples/pull/35/commits/bfad32197d39a343a356457af8d225c76732e281) and share the suggestions if you may have.

I will let @andreivladbrg review it before merging the PR.

**Comment by josechifflet** [comment]
Thank you very much @smol-ninja.

**Comment by andreivladbrg** [comment]
Just had a look at the code, thank you @josechifflet. It looks like you’ve put a lot of effort into this.

I’ve just pushed some polishes to align the code with our coding practices.

@smol-ninja if everything looks good on your end, feel free to merge it

**Review by andreivladbrg — APPROVED** [review]

**Comment by josechifflet** [comment]
Thank you guys, glad to contribute.

**Pull request merged**
